export enum FrameType {
  Effect = "effect",
  EffectPendulum = "effect_pendulum",
  Fusion = "fusion",
  FusionPendulum = "fusion_pendulum",
  Link = "link",
  Normal = "normal",
  NormalPendulum = "normal_pendulum",
  Ritual = "ritual",
  RitualPendulum = "ritual_pendulum",
  Skill = "skill",
  Spell = "spell",
  Synchro = "synchro",
  SynchroPendulum = "synchro_pendulum",
  Token = "token",
  Trap = "trap",
  Xyz = "xyz",
  XyzPendulum = "xyz_pendulum",
}
